++++++++++[>++++++++<-]>+++. // This prints the ASCII value for S(83)
>++++++++++[>+++++++++<-]>+++++++++. //This prints the ASCII value for c(99)
>++++++++++[>++++++++++<-]>++++. //This prints the ASCII value for h(104)
>++++++++++[>+++++++++++<-]>+. //This prints the ASCII value for 0(111)
>++++++++++[>+++++++++++<-]>+. //This prints the ASCII value for 0(111)
>++++++++++[>++++++++++<-]>++++++++. //This prints the ASCII value for l(108)
>++[>+++++<-]>. //This prints the new line character(\n)
